//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FraudSys.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FraudSysResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FraudSysResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FraudSys.Resources.FraudSysResource", typeof(FraudSysResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agência é obrigatória..
        /// </summary>
        internal static string AgenciaObrigatoria {
            get {
                return ResourceManager.GetString("AgenciaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As contas não podem ser iguais..
        /// </summary>
        internal static string AsContasNaoPodemSerIguais {
            get {
                return ResourceManager.GetString("AsContasNaoPodemSerIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a conta destinatário.
        /// </summary>
        internal static string ContaDestinatario {
            get {
                return ResourceManager.GetString("ContaDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta informada não existe..
        /// </summary>
        internal static string ContaInformadaNaoExiste {
            get {
                return ResourceManager.GetString("ContaInformadaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a conta do remetente.
        /// </summary>
        internal static string ContaRemetente {
            get {
                return ResourceManager.GetString("ContaRemetente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF é obrigatório..
        /// </summary>
        internal static string CpfEhObrigatorio {
            get {
                return ResourceManager.GetString("CpfEhObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de CPF {0} inválido..
        /// </summary>
        internal static string FormatoCpfInvalido {
            get {
                return ResourceManager.GetString("FormatoCpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato inválido de agência. Formatos válidos: &quot;1234&quot; ou &quot;1234-5&quot;..
        /// </summary>
        internal static string FormatoInvalidoDeAgencia {
            get {
                return ResourceManager.GetString("FormatoInvalidoDeAgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato inválido de número de conta. A conta deve ter de 5 a 12 dígitos, com dígito verificador (Ex: 123456-7, 12345-6)..
        /// </summary>
        internal static string FormatoInvalidoNumeroDeConta {
            get {
                return ResourceManager.GetString("FormatoInvalidoNumeroDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limite da conta excedido..
        /// </summary>
        internal static string LimiteContaExcedido {
            get {
                return ResourceManager.GetString("LimiteContaExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O limite de transações pix não pode ser negativo..
        /// </summary>
        internal static string LimiteNaoPodeSerNegativo {
            get {
                return ResourceManager.GetString("LimiteNaoPodeSerNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagem não foi fornecida..
        /// </summary>
        internal static string MensagemNaoFornecida {
            get {
                return ResourceManager.GetString("MensagemNaoFornecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível cadastrar uma conta com saldo negativo..
        /// </summary>
        internal static string NaoEhPossivelCadastrarContaComSaldoNegativo {
            get {
                return ResourceManager.GetString("NaoEhPossivelCadastrarContaComSaldoNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível depositar valores negativos..
        /// </summary>
        internal static string NaoEhPossivelDepositarValoresNegativos {
            get {
                return ResourceManager.GetString("NaoEhPossivelDepositarValoresNegativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número da conta é obrigatório..
        /// </summary>
        internal static string NumeroContaObrigatorio {
            get {
                return ResourceManager.GetString("NumeroContaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro desconhecido..
        /// </summary>
        internal static string OcorreuUmErroDesconhecido {
            get {
                return ResourceManager.GetString("OcorreuUmErroDesconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação inválida, não é possível negativar o saldo da conta..
        /// </summary>
        internal static string OperacaoInvalidaNaoEhPossivelNegativarSaldo {
            get {
                return ResourceManager.GetString("OperacaoInvalidaNaoEhPossivelNegativarSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saldo insuficiente para transação..
        /// </summary>
        internal static string SaldoInsuficienteParaTransacao {
            get {
                return ResourceManager.GetString("SaldoInsuficienteParaTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transação aprovada!.
        /// </summary>
        internal static string TransacaoAprovada {
            get {
                return ResourceManager.GetString("TransacaoAprovada", resourceCulture);
            }
        }
    }
}
